name: Laravel Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: windows-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.2'
        architecture: x64
    - uses: actions/checkout@v3
    - name: Copy .env
      run: if not exist .env copy .env.example .env
    - name: Install Dependencies
      run: composer install
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: icacls "storage" /grant:r "%USERNAME%:(OI)(CI)F" /t && icacls "bootstrap/cache" /grant:r "%USERNAME%:(OI)(CI)F" /t
    - name: Create Database
      run: |
        mkdir database
        type nul > database\database.sqlite
    - name: Execute tests (Unit and Feature tests) via PHPUnit/Pest
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database\database.sqlite
      run: php artisan test
